image: docker:stable
services:
  - docker:dind
stages:
  - build
build_image:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $IMAGE_TAG -f dockerfile .
    - docker push $IMAGE_TAG
  only:
    - master

deploy:dev:
  stage: deploy
  script:
    - ssh -p22 $SERVER -i $KEY
    - docker stop rahmen
    - docker rm rahmen
    - docker run -dti --network rahmen_net --name rahmen $IMAGE_TAG
  only:
    - master
