image: docker:stable
variables:
 - All or variables
services:
  - docker:dind
stages:
  - build
  - deploy
build_image:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $IMAGE_TAG -f dockerfile .
    - docker push $IMAGE_TAG
  only:
    - master

deploy_dev:
  stage: deploy
  before_script: 
     - apk add openssh
     - mkdir -p ~/.ssh     
     - echo -e "$KEY" > ~/.ssh/id_rsa     
     - chmod 600 ~/.ssh/id_rsa 
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
  script:
    - ssh -p22 $SERVER < deploy.sh
  only:
    - master
